/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */


// Manual types for Sanity schema and queries
export type BlockContent = {
	_type: 'blockContent';
	// Add more fields as needed
}

export type Category = {
	_type: 'category';
	title: string;
	slug: { current: string };
	description?: string;
}

export type Author = {
	_type: 'author';
	name: string;
	slug: { current: string };
	image?: {
		asset: { _ref: string; _type: string };
		hotspot?: any;
	};
	bio?: BlockContent[];
}

export type Post = {
    _type: string;
    _id: string; // Added _id field
    title: string;
    slug: { current: string };
    author: Author;
    mainImage?: {
        asset: { _ref: string; _type: string };
        alt?: string;
        hotspot?: any;
    };
    categories?: Category[];
    publishedAt?: string;
    body?: BlockContent[];
}

// Query result types
export type PostListItem = {
    _id: string;
    title: string;
    slug: { current: string };
};

// Query result types
export type PostsQueryResult = PostListItem[];
export type PostQueryResult = Pick<Post, 'title' | 'body' | 'mainImage'>;

