/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */


// Manual types for Sanity schema and queries
export type BlockContent = {
	_type: 'blockContent';
	// Add more fields as needed
}

export type Category = {
  _id: string;
  title: string;
  slug: { current: string };
};

export type Author = {
  name: string;
  image?: {
    asset: { _ref: string; _type: string };
    hotspot?: unknown;
  };
};

export type Post = {
  _id: string;
  title: string;
  slug: { current: string };
  body?: any; // You can replace 'any' with your BlockContent[] type if you have it
  mainImage?: {
    asset: { _ref: string; _type: string };
    alt?: string;
    hotspot?: unknown;
  };
  publishedAt?: string;
  categories?: Category[];
  author?: Author;
};

// POSTS_QUERY result type (array of posts)
export type PostsQueryResult = Post[];

// POSTS_SLUGS_QUERY result type (array of slugs)
export type PostSlug = { slug: string };
export type PostsSlugsQueryResult = PostSlug[];

// POST_QUERY result type (single post or null)
export type PostQueryResult = Post | null;

